environment:
  nodejs_version: "Current"

install:
- ps: Install-Product node $env:nodejs_version x64

- appveyor-retry npm install -g npm@latest
- appveyor-retry npm install

test_script:
- appveyor-retry npm test

build: off
